spring.application.name=helloworld
spring.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.datasource.username=postgres
spring.datasource.password=Barath@123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always